### ISSUE TITLE
Add branches

### ISSUE THREAD

**Issue by MatMaul** [flathub/org.kde.PlatformTheme.QGnomePlatform#3]
Could it be possible to branch qt5.11 and qt5.12lts from current master ?
I'll then send patches against them.

Same for https://github.com/flathub/org.kde.KStyle.HighContrast and https://github.com/flathub/org.kde.KStyle.Adwaita.

Thanks.

@nedrichards @TingPing

**Comment by grulja** [comment]
Done.

**Comment by MatMaul** [comment]
@grulja thanks. 5.11 is still plugged on master so you just pushed 5.12 on 5.11 I think by changing to 5.12 on master. To fix this can you merge this and relaunch the builds ?
https://github.com/flathub/buildbot-config/pull/57

**Comment by grulja** [comment]
I created branch "qt5.11" from master, then I created "qt5.12lts" from master and bumped runtime version there to use 5.12 and after that I bumped runtime version also in master to 5.12. It should be correct. I should have first create "qt5.11" branch and bump runtime version in master and from that create "qt5.12lts" branch, but I didn't realize I will be bumping master as well.

**Comment by MatMaul** [comment]
It's pretty fine to have qt5.12 on master, we just need to have the buildbot config in line :) no more master referenced after my changes so this will not happen again.

**Comment by MatMaul** [comment]
I don't know if we understood each other completely but my point is that current builds are wrong :)
In the build properties here https://flathub.org/builds/#/builders/2/builds/7198 you can see that it is 5.11 branch built with the commit "Bump runtime", hence 5.12, right ?

**Comment by MatMaul** [comment]
@grulja Ok nevermind I should have tried it before talking too much, it works perfectly fine, sorry for that.

If I get how buildbot-config is working from the other PR we should create `branch/qt*` instead so it get picked up automatically, can you do that ? Then we can remove them from builds.json, let me know if you want me to send the PR.
Also should we just not remove master and set the default branch to `branch/qt5.12lts` to avoid a double push & build ? Or remove `branch/qt5.12lts` and keep master ?

**Comment by MatMaul** [comment]
Thanks !
