### ISSUE TITLE
The URL in the about section of the project, leads to invalid page

### ISSUE THREAD

**Issue by furkansimsekli** [flathub/org.kde.PlatformTheme.QGnomePlatform#6]
Hi! I was wondering what does this package do, so Googling led me here. Since there is no README, I clicked the URL on the about, but Flathub says:

> App Not Found

> No app with the ID org.kde.PlatformTheme.QGnomePlatform was found on Flathub. Try searching for the app using the search bar above.

**Comment by travier** [comment]
This is expected as this is not an application, but an extension to make Qt apps behave well in GNOME: https://fedoraproject.org/wiki/Changes/QGnomePlatform
