### ISSUE TITLE
Build for 5.15-22.08

### ISSUE THREAD

**Issue by q234rty** [flathub/org.kde.PlatformTheme.QGnomePlatform#7]
Same as title :)

**Comment by travier** [comment]
Pushed the branch. The build is in progress. Which app needs this one? We're still testing the new runtime and haven't announced it yet.

**Comment by q234rty** [comment]
Would be great if you could build [org.kde.WaylandDecoration.QGnomePlatform-decoration](https://github.com/flathub/org.kde.WaylandDecoration.QGnomePlatform-decoration) for 5.15-22.08. The app is [io.github.NhekoReborn.Nheko](https://github.com/flathub/io.github.NhekoReborn.Nheko) and the dev is made aware of your comment in https://github.com/flathub/org.qbittorrent.qBittorrent/pull/90#issuecomment-1244371684 .

**Comment by travier** [comment]
Pushed the branch for https://github.com/flathub/org.kde.WaylandDecoration.QGnomePlatform-decoration
